version: "3"
services:
  grafana-xxl:
    image: monitoringartist/grafana-xxl:5.4
    ports:
      - "3000:3000"
    volumes:
        - grafana_lib:/var/lib/grafana
        - grafana_log:/var/log/grafana
        - grafana_etc:/etc/grafana
    labels:
      team: ito
      app: grafana
volumes:
  grafana_log:
  grafana_etc:
  grafana_lib:
